/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/toast/toast';
import * as import10 from '../../app/pinterest.service';
import * as import11 from '../../app/location.service';
import * as import12 from '../../app/error.service';
import * as import13 from 'ionic-angular/util/events';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from 'ionic-angular/components/content/content';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import29 from 'ionic-angular/components/spinner/spinner';
import * as import30 from '../../node_modules/ionic-angular/components/spinner/spinner.ngfactory';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.ToastController),this.parentInjector.get(import10.PinterestService),this.parentInjector.get(import11.LocationService),this.parentInjector.get(import12.ErrorService),this.parentInjector.get(import13.Events));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HomePage_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import15.ComponentFactory<import3.HomePage> = new import15.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import16.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import17.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import17.NgIf;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import17.NgIf;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import16.Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'alt','logo');
    this.renderer.setElementAttribute(this._el_2,'src','../assets/pin-on-the-go.png');
    this._text_3 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import26.TemplateRef_(this._appEl_4,viewFactory_HomePage1);
    this._NgIf_4_6 = new import17.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_6 = new import2.AppElement(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import26.TemplateRef_(this._appEl_6,viewFactory_HomePage2);
    this._NgIf_6_6 = new import17.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_8 = new import2.AppElement(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import26.TemplateRef_(this._appEl_8,viewFactory_HomePage3);
    this._NgIf_8_6 = new import17.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_3,
        this._appEl_4,
        this._text_5,
        this._appEl_6,
        this._text_7,
        this._appEl_8,
        this._text_9
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import17.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import26.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import17.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import26.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import17.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import16.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    const currVal_1:boolean = (!this.context.userLocation && this.context.userLocationError);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:boolean = (!this.context.userLocation && !this.context.userLocationError);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_6_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.userLocation;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_8_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_0_4.ngOnDestroy();
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('/Users/wassimchegham/Sandbox/oss/pin-on-the-go/.tmp/pages/home/home.html',0,import14.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import27.Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'color','light');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'outline','');
    this.renderer.setElementAttribute(this._el_2,'round','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import27.Button((null as any),'',this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      Request again\n    ',(null as any));
    compView_2.create(this._Button_2_4,[[].concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.outline = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.round = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.requestLocation()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import27.Button;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Spinner_4_4:import29.Spinner;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage2,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'color','light');
    this.renderer.setElementAttribute(this._el_2,'disbaled','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'outline','');
    this.renderer.setElementAttribute(this._el_2,'round','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import27.Button((null as any),'',this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-spinner',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','spinner-crescent');
    this.renderer.setElementAttribute(this._el_4,'color','light');
    this.renderer.setElementAttribute(this._el_4,'margin-right','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import30.viewFactory_Spinner0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Spinner_4_4 = new import29.Spinner(this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Spinner_4_4,[],compView_4);
    compView_4.create(this._Spinner_4_4,[],(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n      Requestion your location...\n    ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.Spinner) && (4 === requestNodeIndex))) { return this._Spinner_4_4; }
    if (((token === import27.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_0:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Button_2_4.outline = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.round = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.color = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_3:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Spinner_4_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_4_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_4:any = this._Spinner_4_4.paused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_4,'spinner-paused',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage2(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import17.NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import17.NgIf;
  _text_5:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage3,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import26.TemplateRef_(this._appEl_2,viewFactory_HomePage4);
    this._NgIf_2_6 = new import17.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import26.TemplateRef_(this._appEl_4,viewFactory_HomePage5);
    this._NgIf_4_6 = new import17.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import26.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import17.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.parent.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage3(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import27.Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage4,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'color','light');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'outline','');
    this.renderer.setElementAttribute(this._el_2,'round','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import27.Button((null as any),'',this.parent.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'Login with Pinterest',(null as any));
    compView_2.create(this._Button_2_4,[[].concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.outline = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.round = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.login()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage4(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import27.Button;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage5,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'color','light');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'outline','');
    this.renderer.setElementAttribute(this._el_2,'round','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import27.Button((null as any),'',this.parent.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    compView_2.create(this._Button_2_4,[[].concat([this._text_3])],(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.outline = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.round = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_4:any = import4.interpolate(1,'Logged as ',this.parent.parent.context.username,' | Logout');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_3,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage5(viewUtils,parentInjector,declarationEl);
}