/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './pins';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/loading/loading';
import * as import10 from '../../app/pinterest.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from '@angular/common/src/directives/ng_class';
import * as import16 from 'ionic-angular/components/content/content';
import * as import17 from 'ionic-angular/components/refresher/refresher';
import * as import18 from 'ionic-angular/components/refresher/refresher-content';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import26 from 'ionic-angular/components/navbar/navbar';
import * as import27 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import28 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import29 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/core/src/security';
import * as import38 from 'ionic-angular/components/card/card';
import * as import39 from 'ionic-angular/components/fab/fab';
import * as import40 from '@angular/core/src/linker/query_list';
import * as import41 from 'ionic-angular/components/icon/icon';
import * as import42 from 'ionic-angular/components/item/item';
import * as import43 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import44 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from 'ionic-angular/util/form';
var renderType_PinsPage_Host:import0.RenderComponentType = (null as any);
class _View_PinsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PinsPage_0_4:import3.PinsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage_Host0,renderType_PinsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-pins',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PinsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PinsPage_0_4 = new import3.PinsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LoadingController),this.parentInjector.get(import10.PinterestService));
    this._appEl_0.initComponent(this._PinsPage_0_4,[],compView_0);
    compView_0.create(this._PinsPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PinsPage) && (0 === requestNodeIndex))) { return this._PinsPage_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._PinsPage_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PinsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PinsPage_Host === (null as any))) { (renderType_PinsPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_PinsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PinsPageNgFactory:import12.ComponentFactory<import3.PinsPage> = new import12.ComponentFactory<import3.PinsPage>('page-pins',viewFactory_PinsPage_Host0,import3.PinsPage);
const styles_PinsPage:any[] = [];
var renderType_PinsPage:import0.RenderComponentType = (null as any);
class _View_PinsPage0 extends import1.AppView<import3.PinsPage> {
  _el_0:any;
  _Header_0_3:import13.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Toolbar_2_4:import13.Toolbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import14.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _NgClass_10_4:import15.NgClass;
  _Content_10_5:import16.Content;
  _text_11:any;
  _el_12:any;
  _Refresher_12_3:import17.Refresher;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _RefresherContent_14_4:import18.RefresherContent;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import19.NgIf;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import19.NgIf;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgFor_24_6:import20.NgFor;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage0,renderType_PinsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this.renderer.setElementAttribute(this._el_0,'no-shadow','');
    this._Header_0_3 = new import13.Header(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'no-border','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import24.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import13.Toolbar(this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import25.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.ToolbarTitle(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_4),this.renderer,this._Toolbar_2_4,this.parentInjector.get(import26.Navbar,(null as any)));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import27.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._NgClass_10_4 = new import15.NgClass(this.parentInjector.get(import28.IterableDiffers),this.parentInjector.get(import29.KeyValueDiffers),new import22.ElementRef(this._el_10),this.renderer);
    this._Content_10_5 = new import16.Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_5,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_12_3 = new import17.Refresher(this._Content_10_5,this.parentInjector.get(import32.NgZone),this.parentInjector.get(import34.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'pullingText','Pull to refresh...');
    this.renderer.setElementAttribute(this._el_14,'refreshingText','Refreshing your nearby pins...');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import35.viewFactory_RefresherContent0(this.viewUtils,this.injector(14),this._appEl_14);
    this._RefresherContent_14_4 = new import18.RefresherContent(this._Refresher_12_3,this.parentInjector.get(import21.Config));
    this._appEl_14.initComponent(this._RefresherContent_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_14.create(this._RefresherContent_14_4,[],(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_19 = new import2.AppElement(19,10,this,this._anchor_19);
    this._TemplateRef_19_5 = new import36.TemplateRef_(this._appEl_19,viewFactory_PinsPage1);
    this._NgIf_19_6 = new import19.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_21 = new import2.AppElement(21,10,this,this._anchor_21);
    this._TemplateRef_21_5 = new import36.TemplateRef_(this._appEl_21,viewFactory_PinsPage2);
    this._NgIf_21_6 = new import19.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_24 = new import2.AppElement(24,10,this,this._anchor_24);
    this._TemplateRef_24_5 = new import36.TemplateRef_(this._appEl_24,viewFactory_PinsPage3);
    this._NgFor_24_6 = new import20.NgFor(this._appEl_24.vcRef,this._TemplateRef_24_5,this.parentInjector.get(import28.IterableDiffers),this.ref);
    this._text_25 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_5,[
      [],
      [].concat([
        this._text_11,
        this._text_17,
        this._text_18,
        this._appEl_19,
        this._text_20,
        this._appEl_21,
        this._text_22,
        this._text_23,
        this._appEl_24,
        this._text_25
      ]
      ),
      [].concat([this._el_12])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {'no-pins': p0};
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'ionRefresh',this.eventHandler(this._handle_ionRefresh_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'ionPull',this.eventHandler(this._handle_ionPull_12_1.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    const subscription_0:any = this._Refresher_12_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_12_0.bind(this)));
    const subscription_1:any = this._Refresher_12_3.ionPull.subscribe(this.eventHandler(this._handle_ionPull_12_1.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import13.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Toolbar_2_4; }
    if (((token === import13.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_0_3; }
    if (((token === import18.RefresherContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RefresherContent_14_4; }
    if (((token === import17.Refresher) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Refresher_12_3; }
    if (((token === import36.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import19.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import36.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import19.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import36.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import20.NgFor) && (24 === requestNodeIndex))) { return this._NgFor_24_6; }
    if (((token === import15.NgClass) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgClass_10_4; }
    if (((token === import16.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Content_10_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_2:any = this._map_0(((this.context.isLoading === false) && (this.context.pins.length === 0)));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_10_4.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_10_4.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_5.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_12_3.ngOnInit(); }
    const currVal_8:any = 'Pull to refresh...';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._RefresherContent_14_4.pullingText = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'Refreshing your nearby pins...';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._RefresherContent_14_4.refreshingText = currVal_9;
      this._expr_9 = currVal_9;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_14_4.ngOnInit(); }
    const currVal_11:any = (this.context.isLoading === true);
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_19_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = ((this.context.isLoading === false) && (this.context.pins.length === 0));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_21_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_13:any = this.context.pins;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgFor_24_6.ngForOf = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgFor_24_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_24_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'Nearby Pins (',this.context.service.minDistance,'km)');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._Content_10_5._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = (this._Refresher_12_3.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_12,'refresher-active',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Refresher_12_3._top;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementStyle(this._el_12,'top',((this.viewUtils.sanitizer.sanitize(import37.SecurityContext.STYLE,currVal_7) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import37.SecurityContext.STYLE,currVal_7).toString()));
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._RefresherContent_14_4.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementAttribute(this._el_14,'state',((currVal_10 == (null as any))? (null as any): currVal_10.toString()));
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Refresher_12_3.ngOnDestroy();
    this._Content_10_5.ngOnDestroy();
  }
  private _handle_ionRefresh_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.refresh($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionPull_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.pulling($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PinsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PinsPage> {
  if ((renderType_PinsPage === (null as any))) { (renderType_PinsPage = viewUtils.createRenderComponentType('/Users/wassimchegham/Sandbox/oss/pin-on-the-go/.tmp/pages/pins/pins.html',0,import11.ViewEncapsulation.None,styles_PinsPage,{})); }
  return new _View_PinsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PinsPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage1,renderType_PinsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      Loading your nearby pins...\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_PinsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PinsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_PinsPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage2,renderType_PinsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      No pins around you...\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_PinsPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PinsPage2(viewUtils,parentInjector,declarationEl);
}
class _View_PinsPage3 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import38.Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _FabContainer_4_4:import39.FabContainer;
  _query_FabButton_4_0:import40.QueryList<any>;
  _query_FabList_4_1:import40.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _FabButton_6_4:import39.FabButton;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import41.Icon;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Item_12_4:import42.Item;
  _ItemContent_12_5:import42.ItemContent;
  _query_Label_12_0:import40.QueryList<any>;
  _query_Button_12_1:import40.QueryList<any>;
  _query_Icon_12_2:import40.QueryList<any>;
  _text_13:any;
  _el_14:any;
  _Icon_14_3:import41.Icon;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import42.Item;
  _ItemContent_23_5:import42.ItemContent;
  _query_Label_23_0:import40.QueryList<any>;
  _query_Button_23_1:import40.QueryList<any>;
  _query_Icon_23_2:import40.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import19.NgIf;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage3,renderType_PinsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import38.Card(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n    \n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'alt','');
    this.renderer.setElementAttribute(this._el_2,'height','200');
    this._text_3 = this.renderer.createText(this._el_0,'\n    \n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_4,'right','');
    this.renderer.setElementAttribute(this._el_4,'top','');
    this._appEl_4 = new import2.AppElement(4,0,this,this._el_4);
    var compView_4:any = import43.viewFactory_FabContainer0(this.viewUtils,this.injector(4),this._appEl_4);
    this._FabContainer_4_4 = new import39.FabContainer(new import22.ElementRef(this._el_4));
    this._query_FabButton_4_0 = new import40.QueryList<any>();
    this._query_FabList_4_1 = new import40.QueryList<any>();
    this._appEl_4.initComponent(this._FabContainer_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'color','danger');
    this.renderer.setElementAttribute(this._el_6,'ion-fab','');
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import43.viewFactory_FabButton0(this.viewUtils,this.injector(6),this._appEl_6);
    this._FabButton_6_4 = new import39.FabButton(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_6),this.renderer);
    this._appEl_6.initComponent(this._FabButton_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','pin');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import41.Icon(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_6.create(this._FabButton_6_4,[[].concat([
        this._text_7,
        this._el_8,
        this._text_9
      ]
    )],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_FabButton_4_0.reset([this._FabButton_6_4]);
    this._FabContainer_4_4._mainButton = this._query_FabButton_4_0.first;
      compView_4.create(this._FabContainer_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_10
      ]
    )],(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this._appEl_12 = new import2.AppElement(12,0,this,this._el_12);
    var compView_12:any = import44.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import42.Item(this.parent.parentInjector.get(import45.Form),this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import42.ItemContent();
    this._query_Label_12_0 = new import40.QueryList<any>();
    this._query_Button_12_1 = new import40.QueryList<any>();
    this._query_Icon_12_2 = new import40.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'item-left','');
    this.renderer.setElementAttribute(this._el_14,'large','');
    this.renderer.setElementAttribute(this._el_14,'name','information-circle');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this._Icon_14_3 = new import41.Icon(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_12_0.reset([]);
    this._Item_12_4.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4,[
      [].concat([this._el_14]),
      [],
      [].concat([
        this._text_13,
        this._text_15,
        this._el_16,
        this._text_18,
        this._el_19,
        this._text_21
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import2.AppElement(23,0,this,this._el_23);
    var compView_23:any = import44.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import42.Item(this.parent.parentInjector.get(import45.Form),this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import42.ItemContent();
    this._query_Label_23_0 = new import40.QueryList<any>();
    this._query_Button_23_1 = new import40.QueryList<any>();
    this._query_Icon_23_2 = new import40.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_28,'item-left','');
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_31 = new import2.AppElement(31,23,this,this._anchor_31);
    this._TemplateRef_31_5 = new import36.TemplateRef_(this._appEl_31,viewFactory_PinsPage4);
    this._NgIf_31_6 = new import19.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [].concat([
        this._el_25,
        this._el_28
      ]
      ),
      [],
      [].concat([
        this._text_24,
        this._text_27,
        this._text_30,
        this._text_32
      ]
      ),
      [],
      [].concat([this._appEl_31])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3; }
    if (((token === import39.FabButton) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._FabButton_6_4; }
    if (((token === import39.FabContainer) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._FabContainer_4_4; }
    if (((token === import41.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3; }
    if (((token === import42.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_12_4; }
    if (((token === import42.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_12_5; }
    if (((token === import36.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import19.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    if (((token === import42.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_23_4; }
    if (((token === import42.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_23_5; }
    if (((token === import38.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_3:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FabButton_6_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_6.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'pin';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_8_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = 'information-circle';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_14_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_12:any = ((this.context.$implicit.metadata == (null as any))? (null as any): ((this.context.$implicit.metadata.place == (null as any))? (null as any): this.context.$implicit.metadata.place.source_url));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_31_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_FabList_4_1.dirty) {
        this._query_FabList_4_1.reset([]);
        this._FabContainer_4_4._fabLists = this._query_FabList_4_1;
        this._query_FabList_4_1.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset([]);
        this._Item_12_4._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset([this._Icon_14_3]);
        this._Item_12_4._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
          this._query_Icon_23_2.reset([this._appEl_31.mapNestedViews(_View_PinsPage4,(nestedView:_View_PinsPage4):any => {
            return [nestedView._Icon_2_3];
        })]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._FabContainer_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this.context.$implicit.image.original.url;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import37.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.note,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'title',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_8_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_14_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',((this.context.$implicit.metadata == (null as any))? (null as any): ((this.context.$implicit.metadata.place == (null as any))? (null as any): this.context.$implicit.metadata.place.name)),'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_17,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.$implicit.note,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_20,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'',((this.context.$implicit.distance == (null as any))? (null as any): this.context.$implicit.distance.time),' min');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_26,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import4.interpolate(1,'(',((this.context.$implicit.distance == (null as any))? (null as any): this.context.$implicit.distance.km),' km)');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_29,currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_8_3.ngOnDestroy();
    this._FabContainer_4_4.ngOnDestroy();
    this._Icon_14_3.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openMaps(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PinsPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PinsPage3(viewUtils,parentInjector,declarationEl);
}
class _View_PinsPage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import41.Icon;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PinsPage4,renderType_PinsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'clear','');
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this.renderer.setElementAttribute(this._el_0,'primary','');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','eye');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import41.Icon(this.parent.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_0,'\n        Start\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'eye';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_2_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PinsPage3>this.parent)._query_Icon_23_2.setDirty();
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.visit(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PinsPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PinsPage4(viewUtils,parentInjector,declarationEl);
}